<a href="https://colab.research.google.com/github/Bindhya-K/NLP/blob/main/WordEmbedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
#Step1. initialize sentences
sentences=['the glass of milk','cup of tea','I am studying','Veda is sleeping','My parents had returned today morning',
           'Satheesh is working','She has exams startinf tomorrow']

In [4]:
# step 2 :vocab size
voc_size=10000

In [5]:
#step2. One Hot Representation
onehot_rep = [one_hot(words,voc_size)for words in sentences]

In [6]:
onehot_rep

[[528, 2590, 5221, 3705],
 [5975, 5221, 5076],
 [6411, 5410, 1986],
 [7526, 5198, 1087],
 [9223, 1701, 7403, 8382, 2750, 3931],
 [5928, 5198, 5112],
 [800, 8845, 7212, 9548, 6264]]

In [7]:
#Step 4: Word Embedding representation(no. of features ahs to be given)
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np



In [8]:
# since each length are of different sizes, we need to make it equal lenth using pad sequence.  let here the sentence length be 8
sent_length = 8
pre_embedding = pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
pre_embedding

array([[   0,    0,    0,    0,  528, 2590, 5221, 3705],
       [   0,    0,    0,    0,    0, 5975, 5221, 5076],
       [   0,    0,    0,    0,    0, 6411, 5410, 1986],
       [   0,    0,    0,    0,    0, 7526, 5198, 1087],
       [   0,    0, 9223, 1701, 7403, 8382, 2750, 3931],
       [   0,    0,    0,    0,    0, 5928, 5198, 5112],
       [   0,    0,    0,  800, 8845, 7212, 9548, 6264]], dtype=int32)

In [9]:
# let the no. of feature be 15
dim=15

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length = sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 15)             150000    
                                                                 
Total params: 150000 (585.94 KB)
Trainable params: 150000 (585.94 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(pre_embedding)

1/1 [==============================] - 0s 112ms/step


array([[[-1.33662112e-02,  3.99571769e-02,  1.50020607e-02,
         -8.77607986e-03,  3.42629664e-02,  2.59725004e-03,
         -4.05475721e-02,  4.58405130e-02,  3.39441411e-02,
          4.88825776e-02, -2.48984583e-02, -2.47989651e-02,
         -1.60341486e-02,  3.75257619e-02,  4.76980209e-03],
        [-1.33662112e-02,  3.99571769e-02,  1.50020607e-02,
         -8.77607986e-03,  3.42629664e-02,  2.59725004e-03,
         -4.05475721e-02,  4.58405130e-02,  3.39441411e-02,
          4.88825776e-02, -2.48984583e-02, -2.47989651e-02,
         -1.60341486e-02,  3.75257619e-02,  4.76980209e-03],
        [-1.33662112e-02,  3.99571769e-02,  1.50020607e-02,
         -8.77607986e-03,  3.42629664e-02,  2.59725004e-03,
         -4.05475721e-02,  4.58405130e-02,  3.39441411e-02,
          4.88825776e-02, -2.48984583e-02, -2.47989651e-02,
         -1.60341486e-02,  3.75257619e-02,  4.76980209e-03],
        [-1.33662112e-02,  3.99571769e-02,  1.50020607e-02,
         -8.77607986e-03,  3.42629664

In [14]:
pre_embedding[0]

array([   0,    0,    0,    0,  528, 2590, 5221, 3705], dtype=int32)

In [15]:
model.predict(pre_embedding[0])

1/1 [==============================] - 0s 47ms/step


array([[-1.3366211e-02,  3.9957177e-02,  1.5002061e-02, -8.7760799e-03,
         3.4262966e-02,  2.5972500e-03, -4.0547572e-02,  4.5840513e-02,
         3.3944141e-02,  4.8882578e-02, -2.4898458e-02, -2.4798965e-02,
        -1.6034149e-02,  3.7525762e-02,  4.7698021e-03],
       [-1.3366211e-02,  3.9957177e-02,  1.5002061e-02, -8.7760799e-03,
         3.4262966e-02,  2.5972500e-03, -4.0547572e-02,  4.5840513e-02,
         3.3944141e-02,  4.8882578e-02, -2.4898458e-02, -2.4798965e-02,
        -1.6034149e-02,  3.7525762e-02,  4.7698021e-03],
       [-1.3366211e-02,  3.9957177e-02,  1.5002061e-02, -8.7760799e-03,
         3.4262966e-02,  2.5972500e-03, -4.0547572e-02,  4.5840513e-02,
         3.3944141e-02,  4.8882578e-02, -2.4898458e-02, -2.4798965e-02,
        -1.6034149e-02,  3.7525762e-02,  4.7698021e-03],
       [-1.3366211e-02,  3.9957177e-02,  1.5002061e-02, -8.7760799e-03,
         3.4262966e-02,  2.5972500e-03, -4.0547572e-02,  4.5840513e-02,
         3.3944141e-02,  4.8882578e-0